version: "3.8"

services:
  postgres:
    container_name: pimi-connect-postgresql
    image: postgres
    restart: no
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password123
